"""Template rendering for customer documents.

Templates are HTML written by staff with {{ placeholders }}. Rendering is deliberately
simple and safe: no expressions or code, only whitelisted keys; every value is HTML-escaped;
table blocks are generated by the server. Template HTML is sanitised on save.
"""
import html
import re
from datetime import date

from backend.database import fetch_one
from backend.services import portal as portal_svc

PLACEHOLDER_RE = re.compile(r"\{\{\s*([a-z_]+(?:\.[a-z_]+)?)\s*\}\}")

# key -> description (shown in the template editor)
FIELDS: dict[str, str] = {
    "company.name": "Company name",
    "company.address": "Company address",
    "company.phone": "Company phone",
    "company.email": "Company email",
    "company.contact": "Phone or email (falls back to 'our office')",
    "today": "Today's date",
    "doc.no": "Document number",
    "doc.title": "Document title",
    "customer.name": "Customer name",
    "customer.father_name": "Father / husband name",
    "customer.cnic": "Customer CNIC",
    "customer.phone": "Customer phone",
    "customer.email": "Customer email",
    "customer.address": "Customer address",
    "booking.no": "Booking number",
    "booking.date": "Booking date",
    "booking.sale_price": "Sale price (PKR)",
    "booking.down_payment": "Booking / down payment (PKR)",
    "booking.paid": "Total paid (PKR)",
    "booking.outstanding": "Outstanding balance (PKR)",
    "booking.pct_paid": "Percent paid",
    "booking.overdue_amount": "Overdue amount (PKR)",
    "booking.possession_date": "Possession date",
    "next_due.date": "Next installment due date",
    "next_due.amount": "Next installment amount (PKR)",
    "unit.no": "Unit number",
    "unit.type": "Unit type",
    "unit.floor": "Floor",
    "unit.area": "Area (sq. yd)",
    "unit.block": "Block / tower",
    "project.name": "Project name",
    "project.location": "Project location",
    "table.installments": "Full payment-plan table",
    "table.payments": "Payments received table",
    "table.overdue": "Overdue installments table",
}

BOOKING_KEYS = {k for k in FIELDS if k.split(".")[0] in ("booking", "next_due", "unit", "project", "table")}

_BAD_TAGS = re.compile(r"<\s*/?\s*(script|iframe|object|embed|link|meta|base|form|input|button|textarea|select|svg|math)\b", re.I)
_BAD_ATTRS = re.compile(r"\son[a-z]+\s*=", re.I)
_BAD_URLS = re.compile(r"(javascript|vbscript)\s*:|data\s*:\s*text/html", re.I)


def template_problems(body_html: str) -> list[str]:
    problems = []
    if len(body_html) > 200_000:
        problems.append("Template is too large")
    if _BAD_TAGS.search(body_html):
        problems.append("Scripts, forms, frames and embedded objects are not allowed")
    if _BAD_ATTRS.search(body_html):
        problems.append("Event-handler attributes (onclick, onload, …) are not allowed")
    if _BAD_URLS.search(body_html):
        problems.append("javascript: / data: URLs are not allowed")
    unknown = sorted({m for m in PLACEHOLDER_RE.findall(body_html) if m not in FIELDS})
    if unknown:
        problems.append("Unknown placeholders: " + ", ".join(unknown))
    return problems


def money(n) -> str:
    try:
        return "PKR " + f"{int(round(n or 0)):,}"
    except (TypeError, ValueError):
        return "PKR 0"


def _d(s) -> str:
    if not s:
        return "—"
    try:
        return date.fromisoformat(str(s)[:10]).strftime("%d %b %Y")
    except ValueError:
        return str(s)


def _e(v) -> str:
    return html.escape("" if v is None else str(v))


def _status_label(s: str | None) -> str:
    return {"paid": "Paid", "partial": "Partly paid", "overdue": "Overdue", "pending": "Upcoming",
            "scheduled": "On milestone", "cancelled": "Cancelled"}.get((s or "").lower(), (s or "—").title())


def _table(headers: list[str], rows: list[list[str]], right: set[int] = frozenset(), empty="No records") -> str:
    th = "".join(f'<th style="text-align:{"right" if i in right else "left"}">{_e(h)}</th>' for i, h in enumerate(headers))
    if not rows:
        return f'<table class="doc-table"><thead><tr>{th}</tr></thead><tbody><tr><td colspan="{len(headers)}">{_e(empty)}</td></tr></tbody></table>'
    body = "".join(
        "<tr>" + "".join(f'<td style="text-align:{"right" if i in right else "left"}">{c}</td>' for i, c in enumerate(r)) + "</tr>"
        for r in rows
    )
    return f'<table class="doc-table"><thead><tr>{th}</tr></thead><tbody>{body}</tbody></table>'


def _company(conn) -> dict:
    rows = conn.execute(
        "SELECT key, value FROM company_settings WHERE key IN ('company_name','company_address','company_phone','company_email')"
    ).fetchall()
    d = {r[0]: r[1] for r in rows}
    return {
        "company.name": d.get("company_name") or "Haven Builders",
        "company.address": d.get("company_address") or "",
        "company.phone": d.get("company_phone") or "",
        "company.email": d.get("company_email") or "",
        "company.contact": d.get("company_phone") or d.get("company_email") or "our office",
    }


def build_context(conn, customer_id: int, booking_id: int | None) -> dict:
    """Return (values, blocks). Values are plain strings (escaped at render time)."""
    portal = portal_svc.get_portal(conn, customer_id)
    if not portal:
        raise ValueError("Customer not found")
    c = portal["customer"]
    ctx: dict[str, str] = {
        **_company(conn),
        "today": date.today().strftime("%d %b %Y"),
        "customer.name": c.get("name") or "",
        "customer.father_name": c.get("father_name") or "",
        "customer.cnic": c.get("cnic") or "",
        "customer.phone": c.get("phone") or "",
        "customer.email": c.get("email") or "",
        "customer.address": c.get("address") or "",
    }
    blocks: dict[str, str] = {}
    if booking_id is None:
        return {"values": ctx, "blocks": blocks}

    b = next((x for x in portal["bookings"] if x["id"] == booking_id), None)
    if not b:
        # Allow non-active bookings too, as long as they belong to this customer.
        owned = fetch_one(conn, "SELECT id FROM bookings WHERE id=? AND customer_id=?", (booking_id, customer_id))
        if not owned:
            raise ValueError("Booking does not belong to this customer")
        raise ValueError("Documents can only be generated for active bookings")
    raw = fetch_one(conn, "SELECT booking_amount FROM bookings WHERE id=?", (booking_id,))
    u = b.get("unit") or {}
    insts = b["installments"]
    live = [i for i in insts if (i.get("status") or "") != "cancelled"]
    overdue = [i for i in live if i.get("status") in ("overdue",) or (i.get("status") == "partial" and i.get("days_overdue"))]
    upcoming = sorted(
        [i for i in live if i.get("status") in ("pending", "partial", "overdue") and (i.get("remaining_amount") or 0) > 0],
        key=lambda i: i.get("due_date") or "9999",
    )
    nxt = upcoming[0] if upcoming else None
    s = b["summary"]
    ctx.update({
        "booking.no": b["booking_no"],
        "booking.date": _d(b["booking_date"]),
        "booking.sale_price": money(s["sale_price"]),
        "booking.down_payment": money(raw["booking_amount"] if raw else 0),
        "booking.paid": money(s["total_paid"]),
        "booking.outstanding": money(s["outstanding"]),
        "booking.pct_paid": f'{s["pct_paid"]}%',
        "booking.overdue_amount": money(sum(i.get("remaining_amount") or 0 for i in overdue)),
        "booking.possession_date": _d(b.get("possession_date")),
        "next_due.date": _d(nxt["due_date"]) if nxt else "—",
        "next_due.amount": money(nxt["remaining_amount"]) if nxt else "—",
        "unit.no": b["unit_no"],
        "unit.type": " · ".join(x for x in (u.get("unit_type"), u.get("residential_type")) if x) or "",
        "unit.floor": "" if u.get("floor_number") is None else str(u.get("floor_number")),
        "unit.area": "" if u.get("area_ghaz") is None else f'{u.get("area_ghaz"):g}',
        "unit.block": u.get("block_tower") or "",
        "project.name": b["project_name"],
        "project.location": b.get("project_location") or "",
    })

    def due_cell(i):
        if i.get("status") == "scheduled":
            return _e(i.get("trigger_label") or "On construction milestone")
        return _e(_d(i.get("due_date")))

    blocks["table.installments"] = _table(
        ["#", "Type", "Due", "Amount", "Paid", "Balance", "Status"],
        [[_e(i.get("installment_no")), _e(i.get("type")), due_cell(i), money(i.get("amount")),
          money(i.get("paid_amount")), money(i.get("remaining_amount")), _e(_status_label(i.get("status")))]
         for i in live],
        right={3, 4, 5},
        empty="No installments on this booking",
    )
    blocks["table.payments"] = _table(
        ["Date", "Receipt", "Against", "Method", "Amount"],
        [[_e(_d(p.get("payment_date"))), _e(p.get("receipt_no") or "—"), _e(p.get("inst_type") or "General"),
          _e(p.get("payment_method") or "—"), money(p.get("amount"))] for p in b["payments"]],
        right={4},
        empty="No payments received yet",
    )
    blocks["table.overdue"] = _table(
        ["#", "Due", "Days late", "Balance"],
        [[_e(i.get("installment_no")), _e(_d(i.get("due_date"))), _e(i.get("days_overdue") or 0),
          money(i.get("remaining_amount"))] for i in overdue],
        right={3},
        empty="Nothing overdue — thank you!",
    )
    return {"values": ctx, "blocks": blocks}


def render(body_html: str, context: dict) -> str:
    values, blocks = context["values"], context["blocks"]

    def sub(m: re.Match) -> str:
        key = m.group(1)
        if key in blocks:
            return blocks[key]
        if key.startswith("table."):
            return '<p class="doc-muted">(Not available — no booking selected)</p>'
        return _e(values.get(key, ""))

    return PLACEHOLDER_RE.sub(sub, body_html)


DOC_CSS = """
*{box-sizing:border-box}
body{margin:0;background:#EEF2F7;font:14px/1.55 'Inter',-apple-system,'Segoe UI',system-ui,sans-serif;color:#0B1B2E}
.toolbar{position:sticky;top:0;display:flex;gap:10px;align-items:center;justify-content:space-between;padding:10px 18px;background:#061A2C;color:#fff;font-size:13px}
.toolbar button,.toolbar a{font:inherit;font-weight:600;border:0;border-radius:8px;padding:8px 14px;cursor:pointer;background:#2563EB;color:#fff;text-decoration:none}
.toolbar a{background:rgba(255,255,255,.12)}
.page{max-width:820px;margin:24px auto;background:#fff;padding:48px 56px;border-radius:6px;box-shadow:0 4px 24px rgba(11,27,46,.1)}
.doc-head{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid #061A2C;padding-bottom:14px;margin-bottom:22px;gap:20px}
.doc-brand{font-size:22px;font-weight:800;letter-spacing:-.02em}
.doc-sub{font-size:12px;color:#5B6B82}
.doc-meta{text-align:right;font-size:12px;color:#5B6B82}
.doc-meta b{color:#0B1B2E}
h1{font-size:20px;margin:0 0 14px}
h2{font-size:15px;margin:22px 0 8px}
p{margin:0 0 10px}
.doc-table{width:100%;border-collapse:collapse;margin:8px 0 16px;font-size:12.5px}
.doc-table th{background:#F1F5F9;text-align:left;padding:7px 9px;border-bottom:2px solid #CBD5E1;font-size:11px;text-transform:uppercase;letter-spacing:.3px;color:#475569}
.doc-table td{padding:7px 9px;border-bottom:1px solid #E2E8F0;font-variant-numeric:tabular-nums}
.doc-grid{display:grid;grid-template-columns:1fr 1fr;gap:4px 24px;margin:6px 0 16px;font-size:13px}
.doc-grid div span{color:#5B6B82}
.doc-box{background:#F8FAFC;border:1px solid #E2E8F0;border-radius:8px;padding:12px 14px;margin:10px 0}
.doc-muted{color:#64748B;font-size:12px}
.doc-sign{display:flex;justify-content:space-between;margin-top:48px;font-size:12px}
.doc-sign div{border-top:1px solid #94A3B8;padding-top:6px;width:200px;text-align:center}
.doc-foot{margin-top:28px;padding-top:10px;border-top:1px solid #E2E8F0;font-size:11px;color:#64748B}
@media print{body{background:#fff}.toolbar{display:none}.page{box-shadow:none;margin:0;max-width:none;padding:0}@page{margin:16mm}}
@media (max-width:640px){.page{margin:0;padding:24px 18px;border-radius:0}.doc-grid{grid-template-columns:1fr}.doc-table{font-size:11px}}
"""


def page_html(title: str, doc_no: str, body: str, back_href: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>{_e(title)} · {_e(doc_no)}</title><style>{DOC_CSS}</style></head>
<body>
<div class="toolbar"><a href="{_e(back_href)}">← Back</a><span>{_e(title)} · {_e(doc_no)}</span><button type="button" id="print-btn">Print / Save PDF</button></div>
<article class="page">{body}</article>
<script src="/static/js/doc-print.js"></script>
</body></html>"""
